name: Daily Scraping

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.0"
      - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r script/requirements.txt
      - name: Activate virtual environment and run scrapers
        run: |
          python script/meetup.py
          python script/luma.py
      - name: Commit and push if changed
        run: |
          git config --global user.name 'benbasic00769'
          git config --global user.email 'shottree657@gmail.com'
          git add *.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update event data" && git push)
